import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import Providers from "@/Providers";
import { PrimeReactProvider } from 'primereact/api';

import '@coreui/coreui-pro/dist/css/coreui.min.css'
import "primereact/resources/themes/lara-light-blue/theme.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GTRAG",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  const value = {
    ripple: true,
  }
  return (
    <html lang="en">
      <head>
      </head>
      <body className={inter.className}>
        <SessionProvider session={session}>
          <PrimeReactProvider value={value}>
            <div className="mx-auto text-2xl gap-2 mb-10">
              {/* <Navbar /> */}
              <Providers>
              {children}
              </Providers>
            </div>
          </PrimeReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
